import { dirname, resolve } from "node:path";
import { fileURLToPath } from "node:url";
import { mkdir, readFile, writeFile } from "node:fs/promises";
import StyleDictionary from "style-dictionary";
import { formattedVariables } from "style-dictionary/utils";

export const TOKENS_DIR = dirname(fileURLToPath(import.meta.url));
const LIGHT = resolve(TOKENS_DIR, "light.json");
const DARK = resolve(TOKENS_DIR, "dark.json");

// light.json is the complete default theme; dark.json holds only overrides.
// The dark build still loads light.json so dark tokens can reference shared
// palette values (e.g. {color.blossom}), then filters its output down to the
// tokens dark.json actually defines.
async function buildVariables(sources, indentation, onlyFrom) {
  const sd = new StyleDictionary({
    source: sources,
    platforms: { css: { transformGroup: "css", prefix: "paster" } },
    log: { verbosity: "silent", warnings: "disabled" },
  });
  await sd.hasInitialized;
  const dictionary = await sd.getPlatformTokens("css");
  if (onlyFrom) {
    dictionary.allTokens = dictionary.allTokens.filter((token) => token.filePath === onlyFrom);
  }
  return formattedVariables({ format: "css", dictionary, formatting: { indentation } });
}

async function renderCss() {
  const light = await buildVariables([LIGHT], "  ");
  const dark = await buildVariables([LIGHT, DARK], "  ", DARK);
  const darkNested = await buildVariables([LIGHT, DARK], "    ", DARK);

  // Dark applies on system preference unless data-theme explicitly chose
  // light, and whenever data-theme explicitly chose dark. Both dark blocks
  // come from the same tokens so they can't drift apart.
  return `/*
 * AUTO-GENERATED by Style Dictionary — do not edit.
 * Edit tokens/light.json or tokens/dark.json instead; this file is
 * regenerated on every build and dev start (see tokens/build.mjs).
 */

:root {
  color-scheme: light;
${light}
}

@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
${darkNested}
  }
}

:root[data-theme="dark"] {
  color-scheme: dark;
${dark}
}
`;
}

/**
 * Writes the themed CSS custom properties to `outFile`. Skips the write when
 * the content is unchanged, so file watchers don't loop on their own output.
 */
export async function buildTokens(outFile) {
  const css = await renderCss();
  const existing = await readFile(outFile, "utf8").catch(() => null);
  if (existing === css) {
    return false;
  }
  await mkdir(dirname(outFile), { recursive: true });
  await writeFile(outFile, css);
  return true;
}
